import json, os

output_file = "/home/basant/Gold-Forex-Prop-Trading/src/data/roadmapData.ts"
os.makedirs(os.path.dirname(output_file), exist_ok=True)

# Define all 11 sections
sections_data = [
  # Section 1
  {
    "id": "intro-forex",
    "title": "Introduction to Forex",
    "phase": 1,
    "description": "Foundational currency mechanics, 24-hour trading session cycles, institutional participants, order types, and leverage foundations.",
    "hubs": [
      {
        "id": "forex-market-basics",
        "title": "Forex Market Basics",
        "category": "Foundations",
        "description": "Core concepts of currency pair quoting, pricing conventions, spread calculation, and pip valuation.",
        "color": "#facc15",
        "leftTopics": [
          {"id": "sydney-session-hours", "title": "Sydney session hours", "side": "left", "description": "Opening window of global trading day (21:00 - 06:00 UTC).", "goldInsight": "XAUUSD consolidates in narrow ranges during Sydney; marks the baseline Asian range.", "propRule": "Avoid large lot sizing during illiquid Sydney hours due to widened broker spreads.", "keyTakeaway": "Mark overnight highs/lows for London sweeps.", "difficulty": "Beginner"},
          {"id": "tokyo-session-hours", "title": "Tokyo session hours", "side": "left", "description": "Asian financial center trading window (00:00 - 09:00 UTC).", "goldInsight": "Asian central banks and institutional flows create early range benchmarks.", "propRule": "Keep risk under 0.25% if trading Asian session due to pre-London fakeouts.", "keyTakeaway": "Asian range highs/lows form primary London targets.", "difficulty": "Beginner"},
          {"id": "london-session-hours", "title": "London session hours", "side": "left", "description": "Highest volume European market window (07:00 - 16:00 UTC).", "goldInsight": "XAUUSD sees its strongest institutional expansion moves between 07:00 and 10:30 UTC.", "propRule": "Prime window for prop evaluation execution; tightest spreads on Gold.", "keyTakeaway": "Focus primary daily setups around the London Open.", "difficulty": "Beginner"},
          {"id": "new-york-session-hours", "title": "New York session hours", "side": "left", "description": "North American window (12:00 - 21:00 UTC) driven by USD data releases.", "goldInsight": "Highest volatility for Gold occurs during NY Open and US data releases (12:30-14:00 UTC).", "propRule": "Check news calendar 15 minutes prior to NY open to prevent news trading violations.", "keyTakeaway": "NY session expands London trend or engineers aggressive daily reversals.", "difficulty": "Beginner"},
          {"id": "session-overlaps", "title": "Session overlaps", "side": "left", "description": "London & New York overlap from 12:00 to 16:00 UTC.", "goldInsight": "The Golden Window where Gold prints its most explosive 100-300 pip trends.", "propRule": "Maximum profit velocity; enforce strict stop losses to avoid rapid drawdown.", "keyTakeaway": "80% of profitable prop traders execute during the London-NY overlap.", "difficulty": "Intermediate"},
          {"id": "liquidity-variations", "title": "Liquidity variations", "side": "left", "description": "Fluctuations in order book depth across market hours.", "goldInsight": "Liquidity drops sharply after 19:00 UTC and during 21:00-22:00 UTC rollover.", "propRule": "Close intraday positions before market rollover to avoid wide spread stopouts.", "keyTakeaway": "Trade only when institutional market makers are actively providing liquidity.", "difficulty": "Intermediate"},
          {"id": "volatility-peaks", "title": "Volatility peaks", "side": "left", "description": "Expansion phases triggered by macro catalysts and session opens.", "goldInsight": "Gold ATR can expand from 150 pips to 600+ pips within minutes of FOMC/NFP.", "propRule": "Halve position size when ATR is at 90th percentile to protect daily limits.", "keyTakeaway": "Volatility creates opportunity only when position sizing is calibrated.", "difficulty": "Intermediate"}
        ],
        "rightTopics": [
          {"id": "currency-pairs-structure", "title": "Currency pairs structure", "side": "right", "description": "Base and quote currency quotation structure (XAU/USD).", "goldInsight": "Gold is priced in USD per troy ounce ($2,500.00 = 1 oz Gold).", "propRule": "Ensure your account pip calculator matches XAUUSD contract specs.", "keyTakeaway": "Analyze USD Index (DXY) as the inverse quote driver of Gold.", "difficulty": "Beginner"},
          {"id": "major-currency-pairs", "title": "Major currency pairs", "side": "right", "description": "Most heavily traded pairs globally (EURUSD, GBPUSD, USDJPY).", "goldInsight": "EURUSD movements correlate strongly with precious metals liquidity.", "propRule": "Do not stack correlated trades exceeding your total daily risk budget.", "keyTakeaway": "Major pairs provide macro sentiment confirmation for Gold.", "difficulty": "Beginner"},
          {"id": "minor-currency-pairs", "title": "Minor currency pairs", "side": "right", "description": "Cross currency pairs excluding the US Dollar.", "goldInsight": "JPY crosses reflect risk-on/risk-off sentiment that spills into gold demand.", "propRule": "Keep prop firm focus on 1-2 instruments (e.g. XAUUSD exclusively).", "keyTakeaway": "Cross pairs reflect sovereign economic strength independent of USD.", "difficulty": "Beginner"},
          {"id": "exotic-currency-pairs", "title": "Exotic currency pairs", "side": "right", "description": "Major currency paired with emerging economy currency.", "goldInsight": "South Africa (USDZAR) is a major physical producer affecting supply metrics.", "propRule": "Avoid trading exotics in prop evaluations due to huge spreads and slippage.", "keyTakeaway": "Exotics carry high carry costs unsuitable for prop rules.", "difficulty": "Intermediate"},
          {"id": "bid-and-ask-prices", "title": "Bid and ask prices", "side": "right", "description": "Price at which market will buy (Bid) vs sell (Ask).", "goldInsight": "Longs open on Ask and close on Bid; shorts open on Bid and close on Ask.", "propRule": "Factor Ask spread into buy stop loss placement to avoid early wicks.", "keyTakeaway": "Understanding the spread differential prevents premature stop hits.", "difficulty": "Beginner"},
          {"id": "spread-definition", "title": "Spread definition", "side": "right", "description": "Difference between Ask and Bid charged by brokers.", "goldInsight": "XAUUSD spreads range 12-25 points during liquid sessions, widening during news.", "propRule": "Never enter Gold trades during 5 minutes before/after rollover.", "keyTakeaway": "Raw spread ECN accounts are mandatory for prop scalping.", "difficulty": "Beginner"},
          {"id": "pip-value-calculation", "title": "Pip value calculation", "side": "right", "description": "Monetary value of single pip/point movement.", "goldInsight": "1 Standard Lot (100 oz) moving $0.10 (1 pip) = $10.00 USD.", "propRule": "Formula: Lots x 100 x (Exit - Entry) = P&L ($). Memorize before trading.", "formulaOrRule": "P&L = Lots × 100 × (Exit Price - Entry Price)", "keyTakeaway": "Accurate pip valuation is the prerequisite for flawless risk control.", "difficulty": "Beginner"}
        ]
      },
      {
        "id": "trading-sessions", "title": "Trading Sessions", "category": "Market Timing",
        "description": "Session dynamics and market overlap liquidity throughout the 24-hour cycle.",
        "color": "#facc15", "leftTopics": [], "rightTopics": []
      },
      {
        "id": "market-participants",
        "title": "Market Participants",
        "category": "Market Structure",
        "description": "Institutional hierarchy driving order flow, wholesale liquidity, and retail execution.",
        "color": "#facc15",
        "leftTopics": [
          {"id": "market-orders", "title": "Market orders", "side": "left", "description": "Executed immediately at best available current market price.", "goldInsight": "Market orders during fast Gold breakouts often suffer 10-30 points slippage.", "propRule": "Prefer limit orders at key support/resistance to eliminate spread penalty.", "keyTakeaway": "Crosses spread immediately against resting liquidity.", "difficulty": "Beginner"},
          {"id": "limit-orders", "title": "Limit orders", "side": "left", "description": "Orders to buy below current price or sell above current price.", "goldInsight": "Placing Buy Limits at institutional Discount Order Blocks catches zero-slippage bounces.", "propRule": "Limit orders ensure exact risk entry and prevent chasing candles.", "keyTakeaway": "Patience in waiting for limit fills preserves risk-to-reward.", "difficulty": "Beginner"},
          {"id": "stop-orders", "title": "Stop orders", "side": "left", "description": "Triggered when price breaks beyond a specific threshold.", "goldInsight": "Used for momentum breakouts above London highs or Asian range extremes.", "propRule": "Ensure prop firm allows stop orders through news events.", "keyTakeaway": "Enters momentum automatically but carries slippage risk.", "difficulty": "Beginner"},
          {"id": "stop-loss-orders", "title": "Stop loss orders", "side": "left", "description": "Non-negotiable risk boundary order limiting maximum loss.", "goldInsight": "Place stop losses beyond structural liquidity points, never at round numbers.", "propRule": "MANDATORY: Prop firms terminate accounts trading without hard stop losses.", "formulaOrRule": "Max Risk = 0.5% - 1.0% of Balance", "keyTakeaway": "Your stop loss is the single most valuable insurance policy.", "difficulty": "Beginner"},
          {"id": "take-profit-orders", "title": "Take profit orders", "side": "left", "description": "Pre-set orders closing positions once target price is reached.", "goldInsight": "Set TPs at opposing liquidity pools (equal highs, unmitigated supply).", "propRule": "Locking in fixed 1:2 or 1:3 R:R prevents giving back evaluation gains.", "keyTakeaway": "Take profits mechanically at planned technical objectives.", "difficulty": "Beginner"},
          {"id": "trailing-stops", "title": "Trailing stops", "side": "left", "description": "Dynamic stop orders tracking favorable price movement.", "goldInsight": "Trail stops behind 15-minute swing lows during trending Gold moves.", "propRule": "Trailing stops protect floating profit towards daily drawdown limits.", "keyTakeaway": "Participate in runaway trends while locking in risk-free gains.", "difficulty": "Intermediate"},
          {"id": "oco-orders", "title": "OCO orders", "side": "left", "description": "One-Cancels-the-Other linked pending orders.", "goldInsight": "Used during range consolidation to straddle breakouts above/below boundaries.", "propRule": "Avoid news straddling if firm prohibits trading red-folder news.", "keyTakeaway": "Automates multi-scenario trading plans without manual intervention.", "difficulty": "Intermediate"}
        ],
        "rightTopics": [
          {"id": "retail-traders", "title": "Retail traders", "side": "right", "description": "Individual traders speculating on personal or prop accounts (~5% volume).", "goldInsight": "Retail herd sentiment creates the liquidity smart money targets.", "propRule": "Do not trade like the 95% retail herd that fails prop evaluations.", "keyTakeaway": "Trade alongside institutional order flow rather than retail emotion.", "difficulty": "Beginner"},
          {"id": "commercial-banks", "title": "Commercial banks", "side": "right", "description": "Tier-1 institutions (JPMorgan, HSBC, UBS) managing bullion flow.", "goldInsight": "Commercial banks execute physical bullion hedges anchoring long-term support.", "propRule": "Understand bank fixing times (London Gold AM 10:30 & PM 15:00 UTC).", "keyTakeaway": "Tier-1 banks are the primary wholesale liquidity providers.", "difficulty": "Intermediate"},
          {"id": "central-banks", "title": "Central banks", "side": "right", "description": "Monetary authorities controlling interest rates, reserves, and money supply.", "goldInsight": "Central banks are net buyers of physical Gold, driving structural multi-year bull runs.", "propRule": "Track Central Bank reserve reports (PBOC gold buying streaks).", "keyTakeaway": "Central banks dictate interest rate cycles and currency debasement.", "difficulty": "Intermediate"},
          {"id": "hedge-funds", "title": "Hedge funds", "side": "right", "description": "Institutional asset managers executing algorithmic and macro momentum.", "goldInsight": "CFTC COT reports reveal speculative hedge fund net long/short positioning.", "propRule": "When hedge fund net long positioning hits historical extremes, watch for sharp flushes.", "keyTakeaway": "Hedge funds drive medium-term trend acceleration.", "difficulty": "Intermediate"},
          {"id": "multinational-corporations", "title": "Multinational corporations", "side": "right", "description": "Corporations exchanging currencies for global trade and raw materials.", "goldInsight": "Tech and jewelry conglomerates buy physical forward contracts regardless of patterns.", "propRule": "Commercial corporate flows can absorb technical levels without warning.", "keyTakeaway": "Corporate hedging represents non-speculative structural market flow.", "difficulty": "Intermediate"},
          {"id": "market-makers", "title": "Market makers", "side": "right", "description": "Firms quoting bid/ask prices to capture spreads and provide liquidity.", "goldInsight": "Market makers engineer liquidity runs into stop clusters before true moves.", "propRule": "Never place stops at obvious equal highs/lows where algorithms sweep.", "keyTakeaway": "Market makers require volume; your stop loss is their liquidity.", "difficulty": "Advanced"},
          {"id": "liquidity-providers", "title": "Liquidity providers", "side": "right", "description": "Prime brokers and non-bank market makers aggregating order books.", "goldInsight": "Prop demo bridges simulate LP fills; fast scalping during low liquidity causes slippage.", "propRule": "Ensure prop firm uses reputable Tier-1 liquidity providers.", "keyTakeaway": "Quality liquidity providers guarantee tight spreads and clean fills.", "difficulty": "Advanced"}
        ]
      },
      {
        "id": "order-types", "title": "Order Types", "category": "Execution",
        "description": "Execution mechanics, pending order types, stop loss safeguards, and automated exits.",
        "color": "#facc15", "leftTopics": [], "rightTopics": []
      },
      {
        "id": "leverage-and-margin",
        "title": "Leverage and Margin",
        "category": "Capital Mechanics",
        "description": "Purchasing power amplification, margin requirements, free margin buffers, and liquidation prevention.",
        "color": "#facc15",
        "leftTopics": [
          {"id": "mt4-interface", "title": "MetaTrader 4 interface", "side": "left", "description": "Legacy standard platform built for fast execution and custom indicators.", "goldInsight": "MT4 lightweight architecture provides millisecond execution for Gold scalping.", "propRule": "Set up hotkeys and one-click trading with lot size scripts in MT4.", "keyTakeaway": "MT4 is widely supported across top-tier prop firms.", "difficulty": "Beginner"},
          {"id": "mt5-features", "title": "MetaTrader 5 features", "side": "left", "description": "Next-gen platform with DOM, native 64-bit speed, and 21 timeframes.", "goldInsight": "MT5 displays real volume tick distribution and multi-timeframe analysis.", "propRule": "Use MT5 built-in economic calendar and order fill policies.", "keyTakeaway": "MT5 provides superior backtesting and order fill precision.", "difficulty": "Beginner"},
          {"id": "ctrader-platform", "title": "cTrader platform", "side": "left", "description": "Direct Market Access platform with level 2 DOM and risk presets.", "goldInsight": "cTrader allows entering positions directly by dollar risk amount.", "propRule": "Take advantage of QuickTrade risk presets to never violate maximum risk.", "keyTakeaway": "cTrader offers the cleanest user interface and native risk controls.", "difficulty": "Intermediate"},
          {"id": "tradingview-integration", "title": "TradingView integration", "side": "left", "description": "Premier web charting platform with cloud sync and multi-asset layouts.", "goldInsight": "Analyze XAUUSD, DXY, US10Y, and Gold futures (GC1!) side-by-side.", "propRule": "Do technical analysis on TradingView and execute on prop terminal.", "keyTakeaway": "TradingView is the golden standard for charting clarity.", "difficulty": "Beginner"},
          {"id": "mobile-trading-apps", "title": "Mobile trading apps", "side": "left", "description": "iOS and Android apps for monitoring positions and modifying stops.", "goldInsight": "Mobile apps are ideal for managing trailing stops; avoid opening new setups.", "propRule": "Do not revenge trade on mobile after taking a loss.", "keyTakeaway": "Use mobile exclusively for risk monitoring, not impulsive execution.", "difficulty": "Beginner"},
          {"id": "order-execution-speed", "title": "Order execution speed", "side": "left", "description": "Latency from order dispatch to execution fill (ms).", "goldInsight": "An extra 200ms latency during high volatility can cost 20-50 pips slippage.", "propRule": "Select prop servers in London (LD4) or New York (NY4) with <20ms latency.", "keyTakeaway": "Low latency ensures stop loss and limit entries fill at exact prices.", "difficulty": "Intermediate"},
          {"id": "charting-tools", "title": "Charting tools", "side": "left", "description": "Drawing suites (Fibonacci, VWAP, volume profile, pitchforks).", "goldInsight": "Fibonacci 61.8% Golden Pocket and Volume Profile POC reign supreme on Gold.", "propRule": "Keep chart layout clean: max 2-3 high-probability tools.", "keyTakeaway": "Master 2-3 institutional tools rather than cluttering charts.", "difficulty": "Beginner"}
        ],
        "rightTopics": [
          {"id": "leverage-mechanics", "title": "Leverage mechanics", "side": "right", "description": "Using borrowed broker capital to control larger contract sizes.", "goldInsight": "1:100 leverage allows controlling $250k Gold position (1 lot) with $2.5k margin.", "propRule": "Never use maximum leverage; size positions by risk percentage (0.5-1%).", "formulaOrRule": "Effective Leverage = Notional ($) / Balance ($)", "keyTakeaway": "Leverage amplifies returns and losses: size by fixed risk.", "difficulty": "Beginner"},
          {"id": "margin-requirements", "title": "Margin requirements", "side": "right", "description": "Minimum collateral held in reserve to keep positions active.", "goldInsight": "XAUUSD margin at 1:100 leverage is 1% of contract value ($2,500/lot).", "propRule": "Over-allocating margin leaves zero room for intraday swings.", "keyTakeaway": "Maintain at least 80% free margin to avoid risk-desk intervention.", "difficulty": "Beginner"},
          {"id": "free-margin", "title": "Free margin", "side": "right", "description": "Account Equity minus Used Margin available for new trades.", "goldInsight": "Declining free margin during volatility restricts scaling and hedging.", "propRule": "If Free Margin drops below 50%, audit open exposure immediately.", "keyTakeaway": "Healthy free margin protects accounts during news spread expansion.", "difficulty": "Beginner"},
          {"id": "margin-call-level", "title": "Margin call level", "side": "right", "description": "Threshold (100% margin level) where broker alerts collateral erosion.", "goldInsight": "A margin call in a prop firm means daily drawdown has already been breached.", "propRule": "Prop traders must never get close to margin calls; drawdown limit hits first.", "keyTakeaway": "If margin call occurs, position sizing strategy has fundamentally failed.", "difficulty": "Beginner"},
          {"id": "stop-out-level", "title": "Stop out level", "side": "right", "description": "Critical margin percentage (50%/30%) where broker liquidates trades.", "goldInsight": "Forced liquidation on Gold occurs at the worst possible market prices.", "propRule": "In prop firms, breach happens at 5-10% drawdown, well before broker stopout.", "keyTakeaway": "Hard stops prevent catastrophic liquidation of a broker stop out.", "difficulty": "Beginner"},
          {"id": "position-sizing", "title": "Position sizing", "side": "right", "description": "Scientific calculation of lot sizes based on dollar risk tolerance.", "goldInsight": "30-pip stop on $100k account risking 1% ($1,000): Lot Size = $1,000 / (30 x $10) = 3.33 Lots.", "propRule": "Calculate position size on EVERY single trade; never guess.", "formulaOrRule": "Lot Size = (Balance × Risk%) / (SL Pips × Pip Value)", "keyTakeaway": "Consistent position sizing separates funded pros from blown accounts.", "difficulty": "Intermediate"},
          {"id": "lot-size-calculation", "title": "Lot size calculation", "side": "right", "description": "Formula translating account balance, stop distance, and point value.", "goldInsight": "Standard Lot = 100 oz ($10/pip). Mini = 10 oz ($1/pip). Micro = 1 oz ($0.10/pip).", "propRule": "Use our built-in Gold Prop Position Size Calculator before every trade.", "keyTakeaway": "Scale lots down as stop expands to keep dollar risk constant.", "difficulty": "Beginner"}
        ]
      },
      {
        "id": "trading-platforms", "title": "Trading Platforms", "category": "Infrastructure",
        "description": "Software ecosystems, execution engines, charting suites, and mobile tools.",
        "color": "#facc15", "leftTopics": [], "rightTopics": []
      }
    ]
  },
  # Section 2
  {
    "id": "gold-fundamentals",
    "title": "Gold Market Fundamentals",
    "phase": 2,
    "description": "XAUUSD macroeconomic drivers, safe haven flows, real interest rate dynamics, central bank buying, and contract specs.",
    "hubs": [
      {
        "id": "gold-as-an-asset",
        "title": "Gold as an Asset",
        "category": "Precious Metals",
        "description": "Physical supply/demand, safe haven characteristics, store of value, and monetary debasement hedge.",
        "color": "#facc15",
        "leftTopics": [
          {"id": "gold-vs-usd", "title": "Gold versus US Dollar", "side": "left", "description": "Inverse correlation between world reserve currency and physical bullion.", "goldInsight": "When DXY rallies on hawkish Fed policy, XAUUSD faces heavy selling pressure.", "propRule": "Confirm Gold direction with DXY trend alignment before high-risk setups.", "keyTakeaway": "Strong Dollar = Headwind; Weak Dollar = Explosive Bullish Gold.", "difficulty": "Beginner"},
          {"id": "pricing-mechanism", "title": "Pricing mechanism", "side": "left", "description": "Interaction of London OTC wholesale fix and COMEX futures pricing.", "goldInsight": "Spot Gold priced per troy ounce (31.1035g) based on continuous global transactions.", "propRule": "Be aware of price discrepancies between CFD brokers and futures benchmarks.", "keyTakeaway": "Wholesale bullion settlement anchors intraday spot market liquidity.", "difficulty": "Intermediate"},
          {"id": "spot-gold-trading", "title": "Spot gold trading", "side": "left", "description": "Over-the-counter spot commodity contracts (XAUUSD).", "goldInsight": "Spot gold allows micro-lot sizing (0.01 = 1 oz) for exact prop risk management.", "propRule": "Most prop firms trade CFD spot gold feeds; verify overnight swap fees.", "keyTakeaway": "Spot trading offers maximum flexibility for intraday challenge risk.", "difficulty": "Beginner"},
          {"id": "gold-futures-contracts", "title": "Gold futures contracts", "side": "left", "description": "Standardized CME/COMEX contracts (GC ticker, 100 troy oz).", "goldInsight": "COMEX futures volume and Open Interest dictate breakout legitimacy on spot charts.", "propRule": "Futures prop firms enforce strict daily contract limits (e.g. max 5 GC contracts).", "keyTakeaway": "Monitor COMEX futures volume bars to confirm institutional conviction.", "difficulty": "Intermediate"},
          {"id": "contract-specifications", "title": "Contract specifications", "side": "left", "description": "Contract size, tick size, minimum lot increments, and swaps.", "goldInsight": "1 Standard Lot = 100 troy oz. Minimum price move is $0.01 ($1.00/lot).", "propRule": "Know your broker multiplier: standard is 100, but some CFDs use 10 or 1000.", "formulaOrRule": "1 Pip on Gold = $0.10 price move = $10.00 on 1.00 Lot", "keyTakeaway": "Confirm contract specs in terminal before trading a new prop account.", "difficulty": "Beginner"},
          {"id": "tick-value-gold", "title": "Tick value of gold", "side": "left", "description": "Smallest price movement value in a financial contract.", "goldInsight": "0.01 tick = $1.00 per standard lot. A $10.00 move yields $1,000 per lot.", "propRule": "A 500-pip Gold flash crash wipes $5,000 on 1 lot; stop discipline is paramount.", "keyTakeaway": "High tick value produces rapid gains and severe drawdown risk.", "difficulty": "Beginner"},
          {"id": "spreads-on-gold", "title": "Spreads on gold", "side": "left", "description": "Difference between buy and sell quotes across liquidity regimes.", "goldInsight": "Normal spread: 12-25 points ($0.12-$0.25). News spread: 100-300 points ($1-$3).", "propRule": "Do not scalp 10-pip targets when spreads are 25 pips; negative expectancy.", "keyTakeaway": "Target minimum 30-50 pip moves on Gold so spreads don't erode edge.", "difficulty": "Beginner"}
        ],
        "rightTopics": [
          {"id": "safe-haven-asset", "title": "Safe haven asset", "side": "right", "description": "Asset expected to retain/increase value during market downturns and crises.", "goldInsight": "During wars, banking panics, or defaults, global capital flees into XAUUSD.", "propRule": "Safe haven breakouts defy resistance; never short a geopolitical panic candle.", "keyTakeaway": "Gold is the ultimate global flight-to-safety asset.", "difficulty": "Beginner"},
          {"id": "inflation-hedge", "title": "Inflation hedge", "side": "right", "description": "Protects purchasing power against fiat devaluation and runaway CPI.", "goldInsight": "Sustained CPI/PPI inflation spikes increase long-term demand for bullion.", "propRule": "Analyze whether inflation is accompanied by rising or falling real yields.", "keyTakeaway": "Gold tracks global money supply (M2) expansion over multi-year cycles.", "difficulty": "Intermediate"},
          {"id": "currency-correlation", "title": "Currency correlation", "side": "right", "description": "Statistical relationships with sovereign currencies (DXY, AUD, JPY, CHF).", "goldInsight": "AUDUSD and XAUUSD share positive correlation (Australia is #2 miner).", "propRule": "Check 30-day rolling correlation before executing correlated cross positions.", "keyTakeaway": "Cross-currency correlations provide leading divergence signals for Gold.", "difficulty": "Intermediate"},
          {"id": "store-of-value", "title": "Store of value", "side": "right", "description": "Asset that can be saved and exchanged without purchasing power loss.", "goldInsight": "Unlike fiat suffering inflation decay, 1 oz Gold maintains real purchasing power.", "propRule": "Store of value status makes Gold less prone to permanent trend collapse.", "keyTakeaway": "Institutional floor anchored by universal recognition as pristine collateral.", "difficulty": "Beginner"},
          {"id": "physical-gold-demand", "title": "Physical gold demand", "side": "right", "description": "Fabrication, coins/bars, ETF holdings (GLD), and institutional vaults.", "goldInsight": "Physical premium spikes on Shanghai Gold Exchange signal Eastern accumulation.", "propRule": "Monitor physical ETF inflows/outflows for weekly macro momentum.", "keyTakeaway": "Physical demand establishes structural bottoms during deep corrections.", "difficulty": "Intermediate"},
          {"id": "industrial-demand", "title": "Industrial demand", "side": "right", "description": "Consumption in electronics, aerospace, nanotechnology, and medicine.", "goldInsight": "Industrial use accounts for 8-10% of annual consumption, creating baseline demand.", "propRule": "Industrial demand reflects global manufacturing and semiconductor health.", "keyTakeaway": "Industrial utility provides a solid physical price floor.", "difficulty": "Intermediate"},
          {"id": "jewelry-demand", "title": "Jewelry demand", "side": "right", "description": "Consumer demand from India (Diwali/weddings) and China (Lunar New Year).", "goldInsight": "Q4 and Q1 seasonality shows bullish strength in XAUUSD due to festivals.", "propRule": "Incorporate seasonal jewelry cycles into monthly swing trading roadmaps.", "keyTakeaway": "Cultural accumulation in India & China drives recurring seasonal tailwinds.", "difficulty": "Intermediate"}
        ]
      },
      {
        "id": "xauusd-dynamics", "title": "XAUUSD Dynamics", "category": "Market Behavior",
        "description": "Intraday price delivery characteristics, tick structure, and spread anomalies.",
        "color": "#facc15", "leftTopics": [], "rightTopics": []
      },
      {
        "id": "macroeconomic-factors",
        "title": "Macroeconomic Factors",
        "category": "Macro Economics",
        "description": "US Dollar index drivers, real yield curves, bond yields, and inflation releases.",
        "color": "#facc15",
        "leftTopics": [
          {"id": "fed-decisions", "title": "Federal Reserve decisions", "side": "left", "description": "FOMC benchmark rate decisions, Dot Plot projections, and press conferences.", "goldInsight": "Fed rate cuts are intensely bullish for Gold (lowers holding cost).", "propRule": "Prop firms prohibit trading near FOMC. Close positions before 18:00 UTC FOMC.", "keyTakeaway": "The Fed is the single most powerful macro catalyst for Gold trends.", "difficulty": "Intermediate"},
          {"id": "interest-rate-hikes", "title": "Interest rate hikes", "side": "left", "description": "Tightening cycles increasing bond yields, creating headwind for Gold.", "goldInsight": "Aggressive rate hikes strengthen USD and yields, suppressing Gold.", "propRule": "During hiking cycles, favor short momentum setups at technical supply zones.", "keyTakeaway": "Interest rate expectations move Gold weeks before decisions occur.", "difficulty": "Intermediate"},
          {"id": "quantitative-easing", "title": "Quantitative easing programs", "side": "left", "description": "Central bank balance sheet expansion and liquidity injections.", "goldInsight": "QE devalues paper currencies and has historically triggered parabolic Gold runs.", "propRule": "QE announcements present high-probability multi-week swing opportunities.", "keyTakeaway": "Liquidity expansion is the rocket fuel for precious metals inflation.", "difficulty": "Advanced"},
          {"id": "monetary-policy-statements", "title": "Monetary policy statements", "side": "left", "description": "Official releases detailing economic outlook and inflation targets.", "goldInsight": "Dovish language ('rate cuts imminent') sends Gold soaring instantly.", "propRule": "Wait 15 minutes post-statement for initial algorithmic fakeouts to clear.", "keyTakeaway": "Analyze tone (Hawkish vs Dovish) to establish institutional conviction.", "difficulty": "Intermediate"},
          {"id": "central-bank-gold-reserves", "title": "Central bank gold reserves", "side": "left", "description": "Sovereign accumulation of physical gold bullion to de-dollarize.", "goldInsight": "Global central banks bought over 1,000 metric tons annually in recent years.", "propRule": "Reserve buying absorbs deep dips, making shorting Gold long-term hazardous.", "keyTakeaway": "Sovereign de-dollarization creates a generational structural bull market.", "difficulty": "Intermediate"},
          {"id": "geopolitical-tensions", "title": "Geopolitical tensions", "side": "left", "description": "Military conflicts, maritime trade disruptions, and international disputes.", "goldInsight": "Geopolitical flare-ups trigger massive weekend price gaps on Gold ($50-$100).", "propRule": "NEVER hold unhedged Gold positions over weekends on prop accounts.", "keyTakeaway": "Geopolitical risk premiums drive sudden parabolic spikes.", "difficulty": "Intermediate"},
          {"id": "global-economic-crises", "title": "Global economic crises", "side": "left", "description": "Banking failures, sovereign debt defaults, and stagflationary shocks.", "goldInsight": "Gold outperforms all asset classes during stagflation.", "propRule": "During crises, reduce risk to 0.25% to withstand heightened volatility.", "keyTakeaway": "Gold is the premier crisis alpha asset for institutional portfolios.", "difficulty": "Intermediate"}
        ],
        "rightTopics": [
          {"id": "dxy-influence", "title": "US Dollar Index influence", "side": "right", "description": "Weighted average of US Dollar against a basket of 6 major currencies.", "goldInsight": "DXY breakout above resistance corresponds to rapid breakdown in XAUUSD 80% of time.", "propRule": "Keep DXY on second monitor to verify dollar strength before buying Gold.", "formulaOrRule": "Inverse Correlation: Gold ↑ when DXY ↓", "keyTakeaway": "Never trade XAUUSD in a vacuum; DXY is your master trend compass.", "difficulty": "Intermediate"},
          {"id": "real-interest-rates", "title": "Real interest rates", "side": "right", "description": "Nominal interest rates minus expected inflation.", "goldInsight": "Real yields have highest statistical correlation with Gold. Negative yields = Mega Bullish.", "propRule": "When US 10-Year TIPS real yield is falling, look for Gold long breakouts.", "formulaOrRule": "Real Yield = Nominal 10Y Yield - Breakeven Inflation", "keyTakeaway": "Real rates dictate fundamental cost of holding gold vs yield-bearing bonds.", "difficulty": "Advanced"},
          {"id": "treasury-yields-impact", "title": "Treasury yields impact", "side": "right", "description": "Return on US government debt obligations (2Y, 10Y, 30Y).", "goldInsight": "Rising 10Y yields make cash attractive, pulling capital out of Gold short term.", "propRule": "Look for divergences: Yields rising but Gold refusing to drop = hidden bull strength.", "keyTakeaway": "Monitor US10Y chart alongside XAUUSD to spot institutional rotation.", "difficulty": "Intermediate"},
          {"id": "inflation-data-releases", "title": "Inflation data releases", "side": "right", "description": "Monthly economic indicators measuring consumer (CPI) and producer (PPI) prices.", "goldInsight": "Higher CPI causes initial Gold dump (fearing rate hikes) followed by rally.", "propRule": "Do not trade first 60 seconds of CPI; wait for 5-minute confirmation candle.", "keyTakeaway": "Differentiate between algorithmic knee-jerk and true multi-hour trend.", "difficulty": "Intermediate"},
          {"id": "employment-reports", "title": "Employment reports", "side": "right", "description": "US Non-Farm Payrolls (NFP), Unemployment Rate, and Hourly Earnings.", "goldInsight": "NFP is most volatile recurring event for Gold, moving 150-300 pips in 3 minutes.", "propRule": "Close or protect positions 10 minutes prior to NFP. Evaluations blow here.", "keyTakeaway": "NFP resets the labor market narrative for the Federal Reserve.", "difficulty": "Intermediate"},
          {"id": "gross-domestic-product", "title": "Gross domestic product", "side": "right", "description": "Quarterly measurement of monetary value of all finished goods/services.", "goldInsight": "Weak GDP prints trigger recession fears, lowering yields and boosting safe haven bids.", "propRule": "Track GDP revisions to gauge underlying economic deceleration.", "keyTakeaway": "Economic slowdown signals future monetary easing, aiding metals.", "difficulty": "Intermediate"},
          {"id": "retail-sales-data", "title": "Retail sales data", "side": "right", "description": "Monthly report tracking consumer spending (~70% of US economic activity).", "goldInsight": "Strong retail sales support USD and create temporary pullbacks in Gold.", "propRule": "Retail Sales releases at 13:30 UTC create clean London/NY breakout setups.", "keyTakeaway": "Consumer resilience gauges whether economy withstands higher rates.", "difficulty": "Intermediate"}
        ]
      },
      {
        "id": "central-bank-policies", "title": "Central Bank Policies", "category": "Monetary Governance",
        "description": "Interest rate cycles, quantitative easing/tightening, and reserve management.",
        "color": "#facc15", "leftTopics": [], "rightTopics": []
      }
    ]
  }
]

print("Base sections prepared.")
